In [1]:
import numpy as np


In [2]:
#create an array of 10 zeros
zeros= np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#create an array of 10 ones
ones= np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
#create array of 10 fives
array=np.ones(10)*5
array


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
array=np.arange(10,50)
print("array of intengers from 10 to 50")
print(array)

array of intengers from 10 to 50
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
#array of all even numbers from 10 to 50
array=np.arange(10,51,2)
print("array of even numbers from 10 to 50")
print(array)

array of even numbers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [18]:
#create a 3*3 matrix with values 0 to 8
matrix=np.matrix([[0,1,2,],[3,4,5],[6,7,8]])
matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [19]:
#identity matrix
matrix=np.matrix([[1,0,0],[0,1,0],[0,0,1]])
matrix

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [23]:
#random number between 0 and 1
rand_num=np.random.normal(0,1)
print('random number between 0 and 1')
print(rand_num)

random number between 0 and 1
-0.1410756060102761


In [24]:
#generate an array of 25 random numbers sampled from standerd normal distribution
rand_num=np.random.normal(0,1,25)
print("25 random numbers of standard distribution")
print(rand_num)

25 random numbers of standard distribution
[-0.86150473  0.25778657 -1.03973901  1.55962106  0.01213265 -0.76893407
 -1.34547226  0.53161074 -0.31576795 -1.0678784   0.87681521 -0.76869298
  0.37294105  1.16949376 -0.07903813  0.27449353  0.76490907  0.60012624
  0.25409809 -0.12046898  0.37049739  0.42690638 -0.82710094  0.01408585
  2.56180402]


In [32]:
random=np.random.rand(20,4)
random

array([[0.30597128, 0.73026289, 0.21057782, 0.86418895],
       [0.77636851, 0.03469605, 0.90771719, 0.28504957],
       [0.96701158, 0.82273382, 0.79232003, 0.34317294],
       [0.63796393, 0.83471214, 0.99438415, 0.42426817],
       [0.78056934, 0.33448212, 0.77913607, 0.76026154],
       [0.86707226, 0.95839964, 0.67036136, 0.12074098],
       [0.20608852, 0.433014  , 0.05691329, 0.7225349 ],
       [0.2580859 , 0.21734215, 0.87649358, 0.69079753],
       [0.99885258, 0.79820973, 0.91730334, 0.96434323],
       [0.81585139, 0.7233453 , 0.16073936, 0.08019848],
       [0.4385084 , 0.34312644, 0.26018796, 0.01279371],
       [0.50718707, 0.72639337, 0.08269797, 0.54348537],
       [0.97375599, 0.57584031, 0.55217389, 0.49447167],
       [0.66999554, 0.71806107, 0.17286833, 0.45869   ],
       [0.61784129, 0.97074666, 0.07396114, 0.90093904],
       [0.16891263, 0.09026184, 0.89138369, 0.84141107],
       [0.78746218, 0.04518887, 0.98968381, 0.57034929],
       [0.73748877, 0.02035842,

In [35]:
#create an array of 20 linearly spaced points between 0 and 1
lin=np.linspace(0,1,20)
lin

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [42]:
#indexing and selection
nums3d=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
nums3d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
#a cell that out puts...
nums2d=np.matrix([[12,13,14,15],[17,18,19,20],[22,23,24,25]])
nums2d

matrix([[12, 13, 14, 15],
        [17, 18, 19, 20],
        [22, 23, 24, 25]])

In [55]:
nums2d=np.array([[2],[7],[12]])
nums2d

array([[ 2],
       [ 7],
       [12]])

In [52]:
#print intengers 20 to 25
nums=np.arange(21,26)
nums


array([21, 22, 23, 24, 25])

In [57]:
nums2d=np.array([[16,15,18,19,20],[21,22,23,24,25]])
nums2d

array([[16, 15, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
#get the sum of all the values in mat
nums=np.arange(1,26).reshape(5,5)
nums


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
#standard deviation
list=(1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26)
print(np.std(list))


7.28
